### ISSUE TITLE
Out-of-date URLs to github commits of profiler binaries in mltk_assets

### ISSUE THREAD

**Issue by shariethernet** [SiliconLabs/mltk#5]
The URLs pointing to the .zip files are out-of-date in the below YAML
mltk\utils\firmware_apps\download_urls.yaml 

To reproduce the error
```mltk profile keyword_spotting.mltk.zip --estimates --full-summary  --device```

Error Log:
```
Time: 2023-08-24 12:09:49
Command-line: profile keyword_spotting.mltk.zip --estimates --full-summary --device
Python version:  3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Python path: D:\ws\mltk\.venv\Scripts\python.exe
Platform: Windows-10-10.0.22621-SP0
MLTK version: 0.18.0
MLTK repo hash: fa2876e1237519e9304407ea4424a88be5e288aa
Extracting keyword_spotting.tflite -> C:/Users/shari/AppData/Local/Temp/shari/mltk/models/keyword_spotting/extracted_files
Up-to-date: https://github.com/SiliconLabs/mltk_assets/raw/master/tools/commander/Commander_win32_x64_1v12p0b1057.zip -> C:/Users/shari/.mltk/tools/commander/v1.12
Programming ML model to device ...
Downloading https://github.com/SiliconLabs/mltk_assets/raw/master/applications/mltk_model_profiler/mltk_model_profiler-brd2601-none-0da859ec.zip
to C:/Users/shari/.mltk/downloads/mltk_model_profiler-brd2601-none-0da859ec.zip
(This may take awhile, please be patient ...)
Failed to profile model
Traceback (most recent call last):
  File "d:\ws\mltk\mltk\cli\profile_mltk_cli.py", line 114, in profile_model_command
    profiling_report = profile_model(
  File "d:\ws\mltk\mltk\core\profile_model.py", line 77, in profile_model
    profiling_model_results = profile_model_on_device(
  File "d:\ws\mltk\mltk\core\profile_model.py", line 210, in profile_model_on_device
    firmware_apps.program_image_with_model(
  File "d:\ws\mltk\mltk\utils\firmware_apps\__init__.py", line 122, in program_image_with_model
    firmware_image_path = get_image(
  File "d:\ws\mltk\mltk\utils\firmware_apps\__init__.py", line 92, in get_image
    download_dir = download_verify_extract(
  File "d:\ws\mltk\mltk\utils\archive_downloader.py", line 129, in download_verify_extract
    download_url(
  File "d:\ws\mltk\mltk\utils\archive_downloader.py", line 331, in download_url
    tmp_filepath, _ = urllib.request.urlretrieve(url, tmp_filepath, t.update_chunk)
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\shari\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Failed to profile model, err: Failed to download: https://github.com/SiliconLabs/mltk_assets/raw/master/applications/mltk_model_profiler/mltk_model_profiler-brd2601-none-0da859ec.zip
```

**Comment by sldriedler** [comment]
Thank you for your feedback. The link has been fixed. Please try running the command again.
